In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from datasets import load_dataset

In [3]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers",split='train')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [4]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [5]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(dataset)

In [8]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [9]:
df = df[['title','abstract']]

In [10]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [11]:
df.shape

(117592, 2)

In [12]:
df=df.head(15000)
df.shape

(15000, 2)

In [13]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [14]:
df["paper_text"]=df["title"]+" "+df["abstract"]

/tmp/ipykernel_7133/529180721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["title"]+" "+df["abstract"]

In [15]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [16]:
type(df[["paper_text"]])

pandas.core.frame.DataFrame

In [17]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [18]:
print(df[["paper_text"]].iloc[0])

paper_text    Learning from compressed observations   The pr...
Name: 0, dtype: object

In [19]:
from sentence_transformers import SentenceTransformer

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [20]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [21]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [22]:
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_7133/2190359946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
/tmp/ipykernel_7133/2190359946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()

In [23]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [24]:
embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [25]:
embedding.shape

(384,)

In [26]:
embedding[:5]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642],
      dtype=float32)

In [27]:
sample_embedding=model.encode(df["paper_text"].head(5).to_list())

In [28]:
print(sample_embedding.shape)

(5, 384)

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))
print(similarity)

[[1.0000001]]

In [31]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))
print(similarity)

[[0.36625272]]

In [32]:
for i in range(1,5):
  similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(similarity)

[[0.36625272]]
[[0.33522844]]
[[0.15505108]]
[[0.37421533]]

Generate embding for all the research paper 15000

In [33]:
import os
import numpy as np

if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings")
    embeddings = np.load("paper_embeddings.npy")
else:
    print("Generating embeddings")
    embeddings = model.encode(df["paper_text"].tolist(), batch_size=32, show_progress_bar=True)
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

Loading saved embeddings

In [34]:
print(sample_embedding)
print(type(embedding))
embedding.dtype

[[-0.1315641  -0.00678266 -0.0036761  ...  0.09561252 -0.04423944
   0.00522624]
 [-0.03589668 -0.06343269 -0.00394966 ...  0.07206137 -0.13262011
  -0.00412079]
 [-0.08129284  0.024103   -0.08868261 ... -0.04524419 -0.0476585
  -0.01549932]
 [-0.10218991 -0.06282566  0.03273673 ... -0.03118814  0.03174181
   0.03621249]
 [-0.08391042  0.01838467 -0.01556663 ... -0.01188403 -0.10644462
   0.00790998]]
<class 'numpy.ndarray'>

dtype('float32')

In [35]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [36]:
import faiss

### Explanation of FAISS Usage

FAISS (Facebook AI Similarity Search) is a library that allows you to quickly search for similarity between vectors. In this notebook, it's used to find research papers whose embeddings are most similar to a given query embedding.

In [37]:
faiss.normalize_L2(embedding.reshape(1,-1))

#### `faiss.normalize_L2(embedding.reshape(1,-1))`

This line normalizes a vector (in this case, a single `embedding`) to have a Euclidean norm (L2 norm) of 1. Normalization is crucial for cosine similarity (which is effectively what inner product search becomes after L2 normalization) because it ensures that the magnitude of the vectors doesn't influence the similarity score, only their direction. `reshape(1,-1)` is used to make sure the single embedding is treated as a 2D array (a single row of a matrix), which FAISS expects.

In [38]:
index=faiss.IndexFlatIP(384)

#### `index=faiss.IndexFlatIP(384)`

This initializes a FAISS index.
*   `IndexFlatIP` creates a simple index that performs an exhaustive search using the inner product (IP) as the similarity metric.
*   `384` is the dimension of the embeddings (the `sample_embedding.shape` and `embedding.shape` showed `(384,)` and `(5, 384)` earlier). The index needs to know the dimension of the vectors it will store and search.

In [39]:
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
query_embedding.shape

(1, 384)

In [70]:
index.add(embeddings)
print(index.ntotal)

15005

#### `index.add(sample_embedding)` and `print(index.ntotal)`

*   `index.add(sample_embedding)` adds your pre-computed embeddings (from `sample_embedding`) to the FAISS index. This is how the index 'learns' about the vectors it needs to search.
*   `index.ntotal` returns the total number of vectors currently stored in the index.

In [41]:
faiss.normalize_L2(query_embedding)

#### `faiss.normalize_L2(query_embedding)`

Just like the embeddings stored in the index, the `query_embedding` (the embedding of your search query) also needs to be L2 normalized before performing the similarity search. This ensures consistent comparison with the normalized vectors in the index.

In [42]:
D,I=index.search(query_embedding,5)
print(D)
print(I)

[[0.24243255 0.17442387 0.14026146 0.07622975 0.01298682]]
[[3 4 0 2 1]]

#### `D,I=index.search(query_embedding,5)`

This is the core search operation:
*   `index.search()` takes two arguments: the query embedding(s) and `k`, the number of nearest neighbors to retrieve.
*   `query_embedding`: The vector representation of your search query.
*   `5`: Specifies that you want the top 5 most similar items.
*   It returns two arrays:
    *   `D`: An array containing the distances (or similarity scores, as Inner Product is used and normalized vectors make it cosine similarity) of the `k` nearest neighbors to each query.
    *   `I`: An array containing the original indices (from your `df` DataFrame) of the `k` nearest neighbors.

In [43]:
print(df.iloc[10466]["title"])
print(df.iloc[13730]["title"])
print(df.iloc[10466]["abstract"])

A Perspective on Deep Imaging
Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [44]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print(f"Title: {df.iloc[idx]['title']}")
    print(f"Abstract: {df.iloc[idx]['abstract'][:300]}")
    print(f"Score: {score}")
  return D,I
  print()

#### `search_paper(query, k=5)` function

This function encapsulates the entire search process:
1.  Takes a `query` string and an optional `k` (number of results) as input.
2.  Encodes the `query` into an embedding using the `model`.
3.  L2-normalizes the `query_embedding`.
4.  Performs the FAISS `search` to get `D` (scores) and `I` (indices).
5.  Iterates through the top `k` results, using the `idx` to retrieve the `title` and a truncated `abstract` from the original `df` DataFrame.
6.  Prints the title, abstract, and similarity score for each result.
7.  Returns the `D` and `I` arrays.

In [45]:
D,I= search_paper("deep learning for medical image analysis")
print(D)
print(I)

Title: A neural network approach to ordinal regression
Abstract:   Ordinal regression is an important type of learning, which has properties of
both classification and regression. Here we describe a simple and effective
approach to adapt a traditional neural network to learn ordinal categories. Our
approach is a generalization of the perceptron method for ordinal
Score: 0.24243254959583282
Title: Parametric Learning and Monte Carlo Optimization
Abstract:   This paper uncovers and explores the close relationship between Monte Carlo
Optimization of a parametrized integral (MCO), Parametric machine-Learning
(PL), and `blackbox' or `oracle'-based optimization (BO). We make four
contributions. First, we prove that MCO is mathematically identical to a bro
Score: 0.17442387342453003
Title: Learning from compressed observations
Abstract:   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to app
Score: 0.1402614563703537
Title: The on-line shortest path problem under partial monitoring
Abstract:   The on-line shortest path problem is considered under various models of
partial monitoring. Given a weighted directed acyclic graph whose edge weights
can change in an arbitrary (adversarial) way, a decision maker has to choose in
each round of a game a path between two distinguished vertices such
Score: 0.0762297511100769
Title: Sensor Networks with Random Links: Topology Design for Distributed
  Consensus
Abstract:   In a sensor network, in practice, the communication among sensors is subject
to:(1) errors or failures at random times; (3) costs; and(2) constraints since
sensors and networks operate under scarce resources, such as power, data rate,
or communication. The signal-to-noise ratio (SNR) is usually a
Score: 0.012986816465854645
[[0.24243255 0.17442387 0.14026146 0.07622975 0.01298682]]
[[3 4 0 2 1]]

In [46]:
search_paper("deep learning for medical image analysis")

Title: A neural network approach to ordinal regression
Abstract:   Ordinal regression is an important type of learning, which has properties of
both classification and regression. Here we describe a simple and effective
approach to adapt a traditional neural network to learn ordinal categories. Our
approach is a generalization of the perceptron method for ordinal
Score: 0.24243254959583282
Title: Parametric Learning and Monte Carlo Optimization
Abstract:   This paper uncovers and explores the close relationship between Monte Carlo
Optimization of a parametrized integral (MCO), Parametric machine-Learning
(PL), and `blackbox' or `oracle'-based optimization (BO). We make four
contributions. First, we prove that MCO is mathematically identical to a bro
Score: 0.17442387342453003
Title: Learning from compressed observations
Abstract:   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to app
Score: 0.1402614563703537
Title: The on-line shortest path problem under partial monitoring
Abstract:   The on-line shortest path problem is considered under various models of
partial monitoring. Given a weighted directed acyclic graph whose edge weights
can change in an arbitrary (adversarial) way, a decision maker has to choose in
each round of a game a path between two distinguished vertices such
Score: 0.0762297511100769
Title: Sensor Networks with Random Links: Topology Design for Distributed
  Consensus
Abstract:   In a sensor network, in practice, the communication among sensors is subject
to:(1) errors or failures at random times; (3) costs; and(2) constraints since
sensors and networks operate under scarce resources, such as power, data rate,
or communication. The signal-to-noise ratio (SNR) is usually a
Score: 0.012986816465854645

(array([[0.24243255, 0.17442387, 0.14026146, 0.07622975, 0.01298682]],
       dtype=float32),
 array([[3, 4, 0, 2, 1]]))

In [47]:
pip install transformers==4.46.3

Requirement already satisfied: transformers==4.46.3 in /usr/local/lib/python3.12/dist-packages (4.46.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (3.29.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.32.4)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2026.6.17)

In [48]:
from transformers import pipeline
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn",
    tokenizer="facebook/bart-large-cnn"
)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [49]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

In [50]:
summary=summarizer(df.iloc[10466]["abstract"],max_length=100,min_length=30,do_sample=False)
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]

In [51]:
print(type(summary))
type(summary[0])

<class 'list'>

dict

In [52]:
  for score,idx in zip(D[0],I[0]):
    print(f"Title: {df.iloc[idx]['title']}")
    print(f"Abstract: {df.iloc[idx]['abstract'][:300]}")
    print(f"Score: {score}")
    print(score)
    summary=summarizer(df.iloc[idx]["abstract"],max_length=100,min_length=30,do_sample=False)
    print(summary)
    print(summary[0]["summary_text"])
    print()

Title: A neural network approach to ordinal regression
Abstract:   Ordinal regression is an important type of learning, which has properties of
both classification and regression. Here we describe a simple and effective
approach to adapt a traditional neural network to learn ordinal categories. Our
approach is a generalization of the perceptron method for ordinal
Score: 0.24243254959583282
0.24243255
[{'summary_text': 'Ordinal regression is an important type of learning, which has properties of both classification and regression. NNRank is a generalization of the perceptron method for ordinal regression. It can learn in both online and batch modes, handling very large training data sets, and making rapid predictions.'}]
Ordinal regression is an important type of learning, which has properties of both classification and regression. NNRank is a generalization of the perceptron method for ordinal regression. It can learn in both online and batch modes, handling very large training data sets, and making rapid predictions.

Title: Parametric Learning and Monte Carlo Optimization
Abstract:   This paper uncovers and explores the close relationship between Monte Carlo
Optimization of a parametrized integral (MCO), Parametric machine-Learning
(PL), and `blackbox' or `oracle'-based optimization (BO). We make four
contributions. First, we prove that MCO is mathematically identical to a bro
Score: 0.17442387342453003
0.17442387
[{'summary_text': 'This paper uncovers and explores the close relationship between Monte CarloOptimization of a parametrized integral (MCO) and Parametric machine-Learning (PL) We prove that MCO is mathematically identical to a broad class of PL problems. We introduce a new version of the Probability Collectives algorithm for blackbox optimization.'}]
This paper uncovers and explores the close relationship between Monte CarloOptimization of a parametrized integral (MCO) and Parametric machine-Learning (PL) We prove that MCO is mathematically identical to a broad class of PL problems. We introduce a new version of the Probability Collectives algorithm for blackbox optimization.

Title: Learning from compressed observations
Abstract:   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to app
Score: 0.1402614563703537
0.14026146
[{'summary_text': 'Predictors are drawn from some specified class, and the goal is to approach the performance (expected loss) of the best predictor in the class. The ideas areillustrated on the example of nonparametric regression in Gaussian noise. Under suitable regularity conditions on the admissible predictors, we give an information-theoretic characterization of achievable predictorperformance.'}]
Predictors are drawn from some specified class, and the goal is to approach the performance (expected loss) of the best predictor in the class. The ideas areillustrated on the example of nonparametric regression in Gaussian noise. Under suitable regularity conditions on the admissible predictors, we give an information-theoretic characterization of achievable predictorperformance.

Title: The on-line shortest path problem under partial monitoring
Abstract:   The on-line shortest path problem is considered under various models of
partial monitoring. Given a weighted directed acyclic graph whose edge weights
can change in an arbitrary (adversarial) way, a decision maker has to choose in
each round of a game a path between two distinguished vertices such
Score: 0.0762297511100769
0.07622975
[{'summary_text': 'The on-line shortest path problem is considered under various models ofpartial monitoring. Given a weighted directed acyclic graph, a decision maker has to choose ineach round of a game a path between two distinguished vertices. The average cumulative loss in n rounds exceeds that of the best path, matched off-line to the entire sequence of the edge weights.'}]
The on-line shortest path problem is considered under various models ofpartial monitoring. Given a weighted directed acyclic graph, a decision maker has to choose ineach round of a game a path between two distinguished vertices. The average cumulative loss in n rounds exceeds that of the best path, matched off-line to the entire sequence of the edge weights.

Title: Sensor Networks with Random Links: Topology Design for Distributed
  Consensus
Abstract:   In a sensor network, in practice, the communication among sensors is subject
to:(1) errors or failures at random times; (3) costs; and(2) constraints since
sensors and networks operate under scarce resources, such as power, data rate,
or communication. The signal-to-noise ratio (SNR) is usually a
Score: 0.012986816465854645
0.0129868165
[{'summary_text': 'In a sensor network, in practice, the communication among sensors is subject to errors or failures at random times. The signal-to-noise ratio (SNR) is usually a main factor in determining the probability of error in a link.'}]
In a sensor network, in practice, the communication among sensors is subject to errors or failures at random times. The signal-to-noise ratio (SNR) is usually a main factor in determining the probability of error in a link.

In [57]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  all_entities=[]
  for score,idx in zip(D[0],I[0]):
    title = df.iloc[idx]['title']
    abstract = df.iloc[idx]['abstract']

    print(f"Title: {title}")
    print()
    print(f"Abstract:")
    print(abstract[:300])
    print()
    print(f"Similarity Score: {score:.3f}")
    print()
    summary=summarizer(abstract,max_length=100,min_length=30,do_sample=False)
    print("Summary:")
    print(summary[0]["summary_text"])
    print()
    keywords = kw_model.extract_keywords(
        abstract,
        keyphrase_ngram_range=(1,2),
        stop_words="english",
        top_n=5
    )
    print("Top Keywords:")
    for keyword, value in keywords:
        print("-", keyword)
    print()
    doc = nlp(abstract)
    print("Named Entities:")
    current_abstract_entities = []
    for entity in doc.ents:
     if entity.text not in current_abstract_entities:
        current_abstract_entities.append(entity.text)
        all_entities.append(entity.text)
        print(f"- {entity.text} ({entity.label_})")

    if not current_abstract_entities:
        print("No entities found in this abstract.")
    print("\n" + "="*70 + "\n")
  print("Most Common Entities Across All Results:")
  print("------------------------------------")

  entity_count = {}
  for name in all_entities:
      if name in entity_count:
          entity_count[name] += 1
      else:
          entity_count[name] = 1

  sorted_entities = sorted(
      entity_count.items(),
      key=lambda x: x[1],
      reverse=True
  )
  print("Top 10 Most Common Entities:\n")
  count = 0
  for name, frequency in sorted_entities:
      print(f"{name} : {frequency}")
      count = count + 1
      if count == 10:
          break
      print()

In [59]:
pip install keybert

Collecting keybert
  Downloading keybert-0.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert) (5.6.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.46.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2.32.4)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2025.11.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2026.6.17)
Downloading keybert-0.9.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 2.1 MB/s eta 0:00:00
Installing collected packages: keybert
Successfully installed keybert-0.9.0

In [60]:
from keybert import KeyBERT

In [61]:
kw_model=KeyBERT(model)
type(kw_model)

keybert._model.KeyBERT

In [62]:
keywords=kw_model.extract_keywords(df.iloc[10466]["abstract"],keyphrase_ngram_range=(1,2),stop_words="english",top_n=5)
print(keywords)

[('imaging deep', 0.5919), ('medical imaging', 0.5281), ('tomographic imaging', 0.525), ('image reconstruction', 0.5095), ('imaging', 0.4528)]

In [63]:
print(df.iloc[10466]["abstract"])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [64]:
text = df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)
print(keywords)
print(type(keywords))
print(type(keywords[0]))

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]
<class 'list'>
<class 'tuple'>

In [65]:
keywords=kw_model.extract_keywords(text,keyphrase_ngram_range=(1,2),stop_words="english",top_n=5)
print(keywords)

[('imaging deep', 0.5919), ('medical imaging', 0.5281), ('tomographic imaging', 0.525), ('image reconstruction', 0.5095), ('imaging', 0.4528)]

In [66]:
def search_and_summarize(query, k=5):

    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)
    all_entities = []
    for score, idx in zip(D[0], I[0]):
        title = df.iloc[idx]["title"]
        abstract = df.iloc[idx]["abstract"]
        print("Title:", title)
        print()
        print("Abstract:")
        print(abstract[:300])
        print()
        print(f"Similarity Score: {score:.3f}")

        if score < 0.20: # Skip if score is below 0.20
            print("Match Level: Too Low. Skipping this paper.\n" + "="*70 + "\n")
            continue

        if score >= 0.70:
            print("Match Level: Highly Similar")
        elif score >= 0.50:
            print("Match Level: Good Match")
        elif score >= 0.30:
            print("Match Level: Moderately Similar")
        else:
            print("Match Level: Weak Match")
        print()
        summary = summarizer(
            abstract,
            max_length=100,
            min_length=30,
            do_sample=False
        )
        print("Summary:")
        print(summary[0]["summary_text"])
        print()
        keywords = kw_model.extract_keywords(
            abstract,
            keyphrase_ngram_range=(1,2),
            stop_words="english",
            top_n=5
        )
        print("Keywords:")
        for keyword, value in keywords:
            print("-", keyword)
        print()
        doc = nlp(abstract)
        print("Named Entities:")
        current_abstract_entities = []
        for entity in doc.ents:
            if entity.text not in current_abstract_entities:
                current_abstract_entities.append(entity.text)
                print(f"- {entity.text} ({entity.label_})")
                if entity.label_ != "CARDINAL" and entity.label_ != "ORDINAL":
                    all_entities.append(entity.text)
        if len(current_abstract_entities) == 0:
            print("No entities found.")
        print("\n" + "=" * 70 + "\n")
    print("Research Insights")
    print("-----------------")
    print("Top 10 Most Common Entities:\n")
    entity_count = {}
    for name in all_entities:
        if name in entity_count:
            entity_count[name] = entity_count[name] + 1
        else:
            entity_count[name] = 1
    sorted_entities = sorted(
        entity_count.items(),
        key=lambda x: x[1],
        reverse=True
    )
    count = 0
    for name, frequency in sorted_entities:
        print(name, ":", frequency)
        count = count + 1
        if count == 10:
            break
    print()

In [67]:
!pip install spacy
!python -m spacy download en_core_web_sm
import spacy
nlp = spacy.load("en_core_web_sm")

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.25.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.4.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.14.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 50.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [68]:
search_and_summarize("machine learning")

Title: A neural network approach to ordinal regression

Abstract:
  Ordinal regression is an important type of learning, which has properties of
both classification and regression. Here we describe a simple and effective
approach to adapt a traditional neural network to learn ordinal categories. Our
approach is a generalization of the perceptron method for ordinal

Similarity Score: 0.353
Match Level: Moderately Similar

Summary:
Ordinal regression is an important type of learning, which has properties of both classification and regression. NNRank is a generalization of the perceptron method for ordinal regression. It can learn in both online and batch modes, handling very large training data sets, and making rapid predictions.

Keywords:
- ranking bioinformatics
- ordinal regression
- learn ordinal
- protein ranking
- classification regression

Named Entities:
- NNRank (ORG)
- Gaussian (NORP)

======================================================================

Title: Parametric Learning and Monte Carlo Optimization

Abstract:
  This paper uncovers and explores the close relationship between Monte Carlo
Optimization of a parametrized integral (MCO), Parametric machine-Learning
(PL), and `blackbox' or `oracle'-based optimization (BO). We make four
contributions. First, we prove that MCO is mathematically identical to a bro

Similarity Score: 0.343
Match Level: Moderately Similar

Summary:
This paper uncovers and explores the close relationship between Monte CarloOptimization of a parametrized integral (MCO) and Parametric machine-Learning (PL) We prove that MCO is mathematically identical to a broad class of PL problems. We introduce a new version of the Probability Collectives algorithm for blackbox optimization.

Keywords:
- carlo optimization
- exploit sample
- immediate sampling
- sampling
- blackbox optimization

Named Entities:
- Monte Carlo
Optimization (PERSON)
- MCO (ORG)
- Parametric (ORG)
- four (CARDINAL)
- First (ORDINAL)
- Second (ORDINAL)
- the Probability Collectives (ORG)
- BO (ORG)
- first (ORDINAL)
- two (CARDINAL)
- third (ORDINAL)
- PL (ORG)

======================================================================

Title: The on-line shortest path problem under partial monitoring

Abstract:
  The on-line shortest path problem is considered under various models of
partial monitoring. Given a weighted directed acyclic graph whose edge weights
can change in an arbitrary (adversarial) way, a decision maker has to choose in
each round of a game a path between two distinguished vertices such

Similarity Score: 0.303
Match Level: Moderately Similar

Summary:
The on-line shortest path problem is considered under various models ofpartial monitoring. Given a weighted directed acyclic graph, a decision maker has to choose ineach round of a game a path between two distinguished vertices. The average cumulative loss in n rounds exceeds that of the best path, matched off-line to the entire sequence of the edge weights.

Keywords:
- bandit problem
- bandit
- bandit setting
- path weights
- weighted directed

Named Entities:
- two (CARDINAL)
- 1/\sqrt{n (CARDINAL)

======================================================================

Title: Learning from compressed observations

Abstract:
  The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to app

Similarity Score: 0.230
Match Level: Weak Match

Summary:
Predictors are drawn from some specified class, and the goal is to approach the performance (expected loss) of the best predictor in the class. The ideas areillustrated on the example of nonparametric regression in Gaussian noise. Under suitable regularity conditions on the admissible predictors, we give an information-theoretic characterization of achievable predictorperformance.

Keywords:
- information theoretic
- admissible predictors
- achievable predictor
- allowable predictors
- statistical learning

Named Entities:
- X$ (MONEY)
- X$-part (MONEY)
- Y$-part (PERSON)
- X$-values (MONEY)
- Gaussian (NORP)

======================================================================

Title: Sensor Networks with Random Links: Topology Design for Distributed
  Consensus

Abstract:
  In a sensor network, in practice, the communication among sensors is subject
to:(1) errors or failures at random times; (3) costs; and(2) constraints since
sensors and networks operate under scarce resources, such as power, data rate,
or communication. The signal-to-noise ratio (SNR) is usually a

Similarity Score: 0.068
Match Level: Too Low. Skipping this paper.
======================================================================

Research Insights
-----------------
Top 10 Most Common Entities:

Gaussian : 2
NNRank : 1
Monte Carlo
Optimization : 1
MCO : 1
Parametric : 1
the Probability Collectives : 1
BO : 1
PL : 1
X$ : 1
X$-part : 1

In [69]:
search_and_summarize("neural network")

Title: A neural network approach to ordinal regression

Abstract:
  Ordinal regression is an important type of learning, which has properties of
both classification and regression. Here we describe a simple and effective
approach to adapt a traditional neural network to learn ordinal categories. Our
approach is a generalization of the perceptron method for ordinal

Similarity Score: 0.413
Match Level: Moderately Similar

Summary:
Ordinal regression is an important type of learning, which has properties of both classification and regression. NNRank is a generalization of the perceptron method for ordinal regression. It can learn in both online and batch modes, handling very large training data sets, and making rapid predictions.

Keywords:
- ranking bioinformatics
- ordinal regression
- learn ordinal
- protein ranking
- classification regression

Named Entities:
- NNRank (ORG)
- Gaussian (NORP)

======================================================================

Title: The on-line shortest path problem under partial monitoring

Abstract:
  The on-line shortest path problem is considered under various models of
partial monitoring. Given a weighted directed acyclic graph whose edge weights
can change in an arbitrary (adversarial) way, a decision maker has to choose in
each round of a game a path between two distinguished vertices such

Similarity Score: 0.181
Match Level: Too Low. Skipping this paper.
======================================================================

Title: Parametric Learning and Monte Carlo Optimization

Abstract:
  This paper uncovers and explores the close relationship between Monte Carlo
Optimization of a parametrized integral (MCO), Parametric machine-Learning
(PL), and `blackbox' or `oracle'-based optimization (BO). We make four
contributions. First, we prove that MCO is mathematically identical to a bro

Similarity Score: 0.167
Match Level: Too Low. Skipping this paper.
======================================================================

Title: Learning from compressed observations

Abstract:
  The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to app

Similarity Score: 0.121
Match Level: Too Low. Skipping this paper.
======================================================================

Title: Sensor Networks with Random Links: Topology Design for Distributed
  Consensus

Abstract:
  In a sensor network, in practice, the communication among sensors is subject
to:(1) errors or failures at random times; (3) costs; and(2) constraints since
sensors and networks operate under scarce resources, such as power, data rate,
or communication. The signal-to-noise ratio (SNR) is usually a

Similarity Score: 0.106
Match Level: Too Low. Skipping this paper.
======================================================================

Research Insights
-----------------
Top 10 Most Common Entities:

NNRank : 1
Gaussian : 1